format = """
$directory\
$git_branch\
$git_status\
$character"""

right_format = """
$python\
$rust\
$zig\
$jobs\
$cmd_duration\
$username\
$localip\
$line_break"""

add_newline = false
palette = 'roadrunner'

[character]
success_symbol = '[>](bold green)'
error_symbol = '[X](bold red)'

[directory]
style = 'bold fg:blue'
format = '[$path ]($style)'
fish_style_pwd_dir_length = 3

[git_branch]
style = 'fg:green'
format = '[on](white) [$branch ]($style)'

[git_status]
staged = '+$count'
modified = '!$count'
untracked = '?$count'
format = '([$ahead_behind$staged$modified](bold brown)[$untracked](bold blue)) '

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[took $duration]($style) '

[localip]
disabled = false

[username]
format = '[$user@]($style)'

[python]
format = 'via [python ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[zig]
format = 'via [zig $version ]($style)'

[palettes.roadrunner]
brown = '#C2A009'
blue = '#00AFFF'
green = '#5FD700'
teal = '#88C0D0'
red = '#ED1517'
orange = '#D08770'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#A8A8A8'
black = '#2E3440'
white='#D8DEE9'
