format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$rust\
$jobs\
$cmd_duration\
$username\
$localip\
$line_break\
$character"""

add_newline = false
palette = 'roadrunner'

[character]
success_symbol = '[>](bold green)'
error_symbol = '[X](bold red)'

[fill]
symbol = ' '

[directory]
style = 'bold fg:blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
style = 'fg:green'
format = '[on](white) [$branch ]($style)'

[git_status]
staged = '+$count'
modified = '!$count'
untracked = '?$count'
format = '([$ahead_behind$staged$modified](bold brown)[$untracked](bold blue))'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[took $duration]($style) '

[localip]
disabled = false

[username]
format = '[$user@]($style)'

[palettes.roadrunner]
brown = '#C2A009'
blue = '#00AFFF'
green = '#5FD700'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#A8A8A8'
black = '#2E3440'
white='#D8DEE9'
